name-template: "$NEXT_MAJOR_VERSION"
tag-template: "$NEXT_MAJOR_VERSION"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Security Enhancements"
    labels:
      - "security"
  - title: "Dependency Updates"
    labels:
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  $CHANGES