on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert ASFF to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert ASFF
        uses: mitre/saf_action@main
        with:
          command_string: 'convert:asff2hdf -i /sample/asff_sample.json -o /output/asff_sample_hdf.json'
      - name: Artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: asff
          path: /output/asff_sample_hdf.json