on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert ASFF to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Sleep for 30 seconds
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '1s'
      - name: Show Inspec Tools Action Deprecation
        uses: mitre/inspec_tools_action@main
        with:
          thresholdfile: hardened.threshold.yml
          resultsfile: ec2_rhel-7_hardened.json
          command: 'compliance'
      - name: Convert ASFF
        uses: em-c-rod/saf_action_test@master
        with:
          command_string: 'convert:asff2hdf -i sample/asff_sample.json -o asff_hdf.json'
      # - name: Artifacts
      #   uses: actions/upload-artifact@v1
      #   if: success()
      #   with:
      #     name: asff
      #     path: output/asff_sample_hdf.json