on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert ASFF to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Sleep for 30 seconds
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '1s'
      # - name: Show Inspec Tools Action Deprecation
      #   uses: mitre/inspec_tools_action@main
      #   with:
      #     thresholdfile: spec/hardened.threshold.yml
      #     resultsfile: spec/ec2_rhel-7_hardened.json
      #     command: 'compliance'
      - name: Convert ASFF to HDF
        uses: mitre/saf_action@v1
        with:
          command_string: 'convert:asff2hdf -i sample/asff_sample.json -o asff_hdf.json'
      # - name: Artifacts
      #   uses: actions/upload-artifact@v1
      #   if: success()
      #   with:
      #     name: asff
      #     path: output/asff_sample_hdf.json
