name: Auto approve and Merge Dependabot PRs
on:
  pull_request_target:
    types: [labeled]
permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    name: Auto-approve dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        # fetch-depth: 0
    - name: Create local changes
      run: |
        npm ci
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated node modules"
        git push origin HEAD:refs/head/${{ github.event.pull_request.head.ref }}
    # - name: Commit & Push Changes
    #   uses: actions-js/push@v1.3
    #   with:
    #     github_token: ${{secrets.GITHUB_TOKEN}}
    #     branch: 'refs/heads/${{ github.event.pull_request.head.sha }}'
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}