on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert Burpsuite to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert Burpsuite
        uses: em-c-rod/saf_action_test@v15
        with:
          command_string: 'convert:burpsuite2hdf -i sample/burpsuite_sample.min -o burpsuite_hdf.json'
      - name: Test view heimdall
        uses: em-c-rod/saf_action_test@v15
        with:
          command_string: 'convert:burpsuite2hdf -i sample/burpsuite_sample.min -o burpsuite_hdf.json'
      - name: Artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: burpsuite
          path: burpsuite_hdf.json