on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert Burpsuite to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert Burpsuite
        uses: mitre/saf_action@main
        with:
          command_string: 'convert:burpsuite2hdf -i /sample/burpsuite_sample.min -o /output/burpsuite_hdf.json'
      - name: Artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: asff
          path: /output/burpsuite_hdf.json