on: [push]
jobs:
  heimdall_tools_conversion:
    runs-on: ubuntu-latest
    name: SAF CLI Convert Burpsuite to HDF
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Show Inspec Tools Action Deprecation
      #   uses: mitre/inspec_tools_action@main
      #   with:
      #     thresholdfile: spec/hardened.threshold.yml
      #     resultsfile: spec/ec2_rhel-7_hardened.json
      #     command: 'compliance'
      # - name: Show Heimdall Tools Action Deprecation
      #   uses: mitre/heimdall_tools_action@deprecateInputs
      #   with:
      #     file: 'sample/burpsuite_sample.min'
      #     converter: 'burpsuite_mapper'
      - name: Convert Burpsuite
        uses: em-c-rod/saf_action_test@master
        with:
          command_string: 'convert burpsuite2hdf -i sample/burpsuite_sample.min -o burpsuite_hdf.json'
      - name: Test view summary
        uses: em-c-rod/saf_action_test@master
        with:
          command_string: 'view:summary -i test/sample_data/red_hat_good.json'
      - name: Artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: burpsuite
          path: burpsuite_hdf.json
