on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release Notes
        run: |
          echo "$(git tag -l --sort=committerdate)"
          echo "$(git tag -l --sort=committerdate --format="%(contents:subject)" | head -n 1)" > RELEASE_NOTES
          echo "This release corresponds to the latest of the same major version for the SAF CLI." >> RELEASE_NOTES
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE_NOTES